backend:
  name: github
  repo: nhammond101/netlify-gatsby

# This line should *not* be indented
publish_mode: editorial_workflow

media_folder: static/assets
public_folder: assets

collections:
  - name: landing
    label: Landing
    folder: content/landing
    create: true
    fields:
      - { name: title, label: "Title" }
      - { name: heroImage, label: "Hero Image", widget: image }
      - { name: howToPlay, label: "How To Play", widget: image }
      - { name: description, label: "Description", widget: text }
      - { name: bottomHero, label: "Bottom Hero", widget: image }
      - { name: testimonialImage, label: "Testimonial Image", widget: image }
      - { name: testimonialText, label: "Testimonial Text", widget: text }
      - { name: charities, label: "Charities", widget: image }
